-- generated by scripts/gen-sqlite-ddl.cjs — do not edit by hand
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS "User" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "email" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "provider" TEXT NOT NULL DEFAULT 'email',
  "providerId" TEXT,
  "passwordHash" TEXT,
  "isPlatformAdmin" BOOLEAN NOT NULL DEFAULT false,
  "status" TEXT NOT NULL DEFAULT 'active',
  "emailVerifiedAt" DATETIME,
  "phone" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");
CREATE TABLE IF NOT EXISTS "Academy" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "intro" TEXT,
  "color" TEXT NOT NULL DEFAULT '#2563eb',
  "logoPath" TEXT,
  "representativeName" TEXT,
  "phone" TEXT,
  "region" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "plan" TEXT NOT NULL DEFAULT 'free',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "Academy_slug_key" ON "Academy"("slug");
CREATE TABLE IF NOT EXISTS "AcademyMember" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "isTeacher" BOOLEAN NOT NULL DEFAULT true,
  "status" TEXT NOT NULL DEFAULT 'active',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AcademyMember_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "AcademyMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "AcademyMember_academyId_userId_key" ON "AcademyMember"("academyId", "userId");
CREATE INDEX IF NOT EXISTS "AcademyMember_userId_idx" ON "AcademyMember"("userId");
CREATE TABLE IF NOT EXISTS "Invitation" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "isTeacher" BOOLEAN NOT NULL DEFAULT true,
  "email" TEXT,
  "name" TEXT,
  "tokenHash" TEXT NOT NULL,
  "expiresAt" DATETIME NOT NULL,
  "usedAt" DATETIME,
  "revokedAt" DATETIME,
  "createdBy" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Invitation_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Invitation_tokenHash_key" ON "Invitation"("tokenHash");
CREATE INDEX IF NOT EXISTS "Invitation_academyId_usedAt_idx" ON "Invitation"("academyId", "usedAt");
CREATE TABLE IF NOT EXISTS "Subscription" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "provider" TEXT NOT NULL DEFAULT 'mock',
  "providerCustomerId" TEXT,
  "providerSubscriptionId" TEXT,
  "seatQuantity" INTEGER NOT NULL DEFAULT 1,
  "unitPrice" INTEGER NOT NULL DEFAULT 9900,
  "status" TEXT NOT NULL DEFAULT 'active',
  "currentPeriodStart" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "currentPeriodEnd" DATETIME,
  "cardLast4" TEXT,
  "lastPaymentAt" DATETIME,
  "lastPaymentError" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Subscription_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Subscription_academyId_key" ON "Subscription"("academyId");
CREATE TABLE IF NOT EXISTS "Payment" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "subscriptionId" TEXT NOT NULL,
  "amount" INTEGER NOT NULL,
  "seatQuantity" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "providerRef" TEXT,
  "error" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Payment_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "Subscription" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "Payment_subscriptionId_createdAt_idx" ON "Payment"("subscriptionId", "createdAt");
CREATE TABLE IF NOT EXISTS "SignupSession" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "tokenHash" TEXT NOT NULL,
  "step" INTEGER NOT NULL DEFAULT 1,
  "academyName" TEXT,
  "representativeName" TEXT,
  "phone" TEXT,
  "region" TEXT,
  "teacherCount" INTEGER NOT NULL DEFAULT 1,
  "ownerIsTeacher" BOOLEAN NOT NULL DEFAULT true,
  "ownerName" TEXT,
  "email" TEXT,
  "passwordHash" TEXT,
  "verifyTokenHash" TEXT,
  "verifyTokenDev" TEXT,
  "verifySentAt" DATETIME,
  "verifiedAt" DATETIME,
  "userId" TEXT,
  "academyId" TEXT,
  "completedAt" DATETIME,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expiresAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "SignupSession_tokenHash_key" ON "SignupSession"("tokenHash");
CREATE UNIQUE INDEX IF NOT EXISTS "SignupSession_verifyTokenHash_key" ON "SignupSession"("verifyTokenHash");
CREATE TABLE IF NOT EXISTS "ClassRoom" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "archived" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ClassRoom_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "ClassRoom_academyId_idx" ON "ClassRoom"("academyId");
CREATE TABLE IF NOT EXISTS "Student" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "classId" TEXT,
  "name" TEXT NOT NULL,
  "school" TEXT,
  "grade" TEXT,
  "memo" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "userId" TEXT,
  "inviteTokenHash" TEXT,
  "inviteExpiresAt" DATETIME,
  "inviteSentAt" DATETIME,
  "status" TEXT NOT NULL DEFAULT 'active',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Student_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Student_classId_fkey" FOREIGN KEY ("classId") REFERENCES "ClassRoom" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "Student_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Student_inviteTokenHash_key" ON "Student"("inviteTokenHash");
CREATE UNIQUE INDEX IF NOT EXISTS "Student_academyId_userId_key" ON "Student"("academyId", "userId");
CREATE INDEX IF NOT EXISTS "Student_academyId_classId_idx" ON "Student"("academyId", "classId");
CREATE TABLE IF NOT EXISTS "TeacherStudent" (
  "memberId" TEXT NOT NULL,
  "studentId" TEXT NOT NULL,
  PRIMARY KEY ("memberId", "studentId"),
  CONSTRAINT "TeacherStudent_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "AcademyMember" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "TeacherStudent_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "StudentLinkRequest" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "studentId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "decidedAt" DATETIME,
  "decidedBy" TEXT,
  CONSTRAINT "StudentLinkRequest_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "StudentLinkRequest_studentId_status_idx" ON "StudentLinkRequest"("studentId", "status");
CREATE TABLE IF NOT EXISTS "VocabBook" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "createdById" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "level" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "VocabBook_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "VocabBook_academyId_idx" ON "VocabBook"("academyId");
CREATE TABLE IF NOT EXISTS "BookDay" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "bookId" TEXT NOT NULL,
  "dayNo" INTEGER NOT NULL,
  "label" TEXT NOT NULL,
  CONSTRAINT "BookDay_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "VocabBook" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "BookDay_bookId_dayNo_key" ON "BookDay"("bookId", "dayNo");
CREATE TABLE IF NOT EXISTS "Word" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "bookId" TEXT NOT NULL,
  "dayId" TEXT NOT NULL,
  "english" TEXT NOT NULL,
  "pos" TEXT,
  "meaning" TEXT NOT NULL,
  "synonyms" TEXT,
  "section" TEXT,
  "approved" BOOLEAN NOT NULL DEFAULT true,
  "excluded" BOOLEAN NOT NULL DEFAULT false,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Word_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "VocabBook" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Word_dayId_fkey" FOREIGN KEY ("dayId") REFERENCES "BookDay" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "Word_bookId_dayId_idx" ON "Word"("bookId", "dayId");
CREATE TABLE IF NOT EXISTS "WordRevision" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "wordId" TEXT NOT NULL,
  "revision" INTEGER NOT NULL,
  "english" TEXT NOT NULL,
  "pos" TEXT,
  "meaning" TEXT NOT NULL,
  "changedBy" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "WordRevision_wordId_fkey" FOREIGN KEY ("wordId") REFERENCES "Word" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Import" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "bookId" TEXT,
  "createdById" TEXT NOT NULL,
  "fileName" TEXT NOT NULL,
  "fileType" TEXT NOT NULL,
  "filePath" TEXT NOT NULL,
  "fileSize" INTEGER NOT NULL,
  "sha256" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'queued',
  "warnings" TEXT NOT NULL DEFAULT '[]',
  "meta" TEXT NOT NULL DEFAULT '{}',
  "errorCode" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Import_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Import_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "VocabBook" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "Import_academyId_status_idx" ON "Import"("academyId", "status");
CREATE TABLE IF NOT EXISTS "ImportRow" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "importId" TEXT NOT NULL,
  "seq" INTEGER NOT NULL,
  "dayLabel" TEXT,
  "dayNo" INTEGER,
  "english" TEXT NOT NULL,
  "pos" TEXT,
  "meaning" TEXT NOT NULL,
  "synonyms" TEXT,
  "section" TEXT,
  "source" TEXT NOT NULL DEFAULT '',
  "warning" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  CONSTRAINT "ImportRow_importId_fkey" FOREIGN KEY ("importId") REFERENCES "Import" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "ImportRow_importId_idx" ON "ImportRow"("importId");
CREATE TABLE IF NOT EXISTS "Exam" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "bookId" TEXT NOT NULL,
  "createdById" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "questionCount" INTEGER NOT NULL DEFAULT 40,
  "passScore" INTEGER NOT NULL DEFAULT 90,
  "timeLimitMin" INTEGER,
  "secondsPerItem" INTEGER NOT NULL DEFAULT 7,
  "scoreVisibility" TEXT NOT NULL DEFAULT 'immediate',
  "answerVisibility" TEXT NOT NULL DEFAULT 'after_release',
  "answersReleased" BOOLEAN NOT NULL DEFAULT false,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "isRetake" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Exam_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Exam_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "VocabBook" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "Exam_academyId_status_idx" ON "Exam"("academyId", "status");
CREATE TABLE IF NOT EXISTS "ExamScope" (
  "examId" TEXT NOT NULL,
  "dayId" TEXT NOT NULL,
  PRIMARY KEY ("examId", "dayId"),
  CONSTRAINT "ExamScope_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "ExamForm" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "examId" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "hash" TEXT,
  "seed" TEXT NOT NULL,
  "warnings" TEXT NOT NULL DEFAULT '[]',
  "publishedAt" DATETIME,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ExamForm_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "ExamForm_examId_version_key" ON "ExamForm"("examId", "version");
CREATE TABLE IF NOT EXISTS "FormItem" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "formId" TEXT NOT NULL,
  "position" INTEGER NOT NULL,
  "wordId" TEXT NOT NULL,
  "prompt" TEXT NOT NULL,
  "dayLabel" TEXT NOT NULL,
  CONSTRAINT "FormItem_formId_fkey" FOREIGN KEY ("formId") REFERENCES "ExamForm" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "FormItem_wordId_fkey" FOREIGN KEY ("wordId") REFERENCES "Word" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "FormItem_formId_position_key" ON "FormItem"("formId", "position");
CREATE TABLE IF NOT EXISTS "FormOption" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "itemId" TEXT NOT NULL,
  "position" INTEGER NOT NULL,
  "text" TEXT NOT NULL,
  "isCorrect" BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT "FormOption_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "FormItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "FormOption_itemId_position_key" ON "FormOption"("itemId", "position");
CREATE TABLE IF NOT EXISTS "Assignment" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "examId" TEXT NOT NULL,
  "formId" TEXT NOT NULL,
  "studentId" TEXT NOT NULL,
  "mode" TEXT,
  "startAt" DATETIME,
  "dueAt" DATETIME,
  "status" TEXT NOT NULL DEFAULT 'assigned',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Assignment_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Assignment_formId_fkey" FOREIGN KEY ("formId") REFERENCES "ExamForm" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "Assignment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Assignment_examId_studentId_key" ON "Assignment"("examId", "studentId");
CREATE INDEX IF NOT EXISTS "Assignment_studentId_status_idx" ON "Assignment"("studentId", "status");
CREATE TABLE IF NOT EXISTS "Attempt" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "assignmentId" TEXT NOT NULL,
  "attemptNo" INTEGER NOT NULL DEFAULT 1,
  "mode" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'in_progress',
  "revision" INTEGER NOT NULL DEFAULT 0,
  "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deadlineAt" DATETIME,
  "submittedAt" DATETIME,
  CONSTRAINT "Attempt_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "Assignment" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "Attempt_assignmentId_idx" ON "Attempt"("assignmentId");
CREATE TABLE IF NOT EXISTS "AttemptAnswer" (
  "attemptId" TEXT NOT NULL,
  "itemId" TEXT NOT NULL,
  "optionId" TEXT,
  "updatedAt" DATETIME NOT NULL,
  PRIMARY KEY ("attemptId", "itemId"),
  CONSTRAINT "AttemptAnswer_attemptId_fkey" FOREIGN KEY ("attemptId") REFERENCES "Attempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "AttemptAnswer_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "FormItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "AttemptAnswer_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "FormOption" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "GradeRevision" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "attemptId" TEXT NOT NULL,
  "revisionNo" INTEGER NOT NULL,
  "correctCount" INTEGER NOT NULL,
  "totalCount" INTEGER NOT NULL,
  "score" REAL NOT NULL,
  "passed" BOOLEAN NOT NULL,
  "reason" TEXT NOT NULL DEFAULT 'initial',
  "itemResults" TEXT NOT NULL,
  "createdBy" TEXT,
  "current" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GradeRevision_attemptId_fkey" FOREIGN KEY ("attemptId") REFERENCES "Attempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "GradeRevision_attemptId_revisionNo_key" ON "GradeRevision"("attemptId", "revisionNo");
CREATE TABLE IF NOT EXISTS "PrintInstance" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "attemptId" TEXT NOT NULL,
  "formId" TEXT NOT NULL,
  "pdfPath" TEXT NOT NULL,
  "manifest" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "templateVersion" TEXT NOT NULL DEFAULT 'v1',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PrintInstance_attemptId_fkey" FOREIGN KEY ("attemptId") REFERENCES "Attempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "PrintInstance_formId_fkey" FOREIGN KEY ("formId") REFERENCES "ExamForm" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "PrintPage" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "printInstanceId" TEXT NOT NULL,
  "pageNo" INTEGER NOT NULL,
  "token" TEXT NOT NULL,
  CONSTRAINT "PrintPage_printInstanceId_fkey" FOREIGN KEY ("printInstanceId") REFERENCES "PrintInstance" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "PrintPage_token_key" ON "PrintPage"("token");
CREATE UNIQUE INDEX IF NOT EXISTS "PrintPage_printInstanceId_pageNo_key" ON "PrintPage"("printInstanceId", "pageNo");
CREATE TABLE IF NOT EXISTS "ScanUpload" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "uploadedById" TEXT NOT NULL,
  "filePath" TEXT NOT NULL,
  "fileName" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'queued',
  "source" TEXT NOT NULL DEFAULT 'teacher',
  "pageId" TEXT,
  "detections" TEXT NOT NULL DEFAULT '[]',
  "reviewed" TEXT NOT NULL DEFAULT '{}',
  "correctedPath" TEXT,
  "errorCode" TEXT,
  "reviewNotes" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "ScanUpload_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "ScanUpload_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "PrintPage" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "ScanUpload_academyId_status_idx" ON "ScanUpload"("academyId", "status");
CREATE TABLE IF NOT EXISTS "RetakeTask" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "studentId" TEXT NOT NULL,
  "sourceAttemptId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "dueAt" DATETIME,
  "scheduledAt" DATETIME,
  "note" TEXT,
  "retakeExamId" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" DATETIME,
  CONSTRAINT "RetakeTask_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "RetakeTask_sourceAttemptId_fkey" FOREIGN KEY ("sourceAttemptId") REFERENCES "Attempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "RetakeTask_sourceAttemptId_key" ON "RetakeTask"("sourceAttemptId");
CREATE UNIQUE INDEX IF NOT EXISTS "RetakeTask_sourceAttemptId_key" ON "RetakeTask"("sourceAttemptId");
CREATE TABLE IF NOT EXISTS "Job" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT,
  "type" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "idempotencyKey" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'queued',
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "payload" TEXT NOT NULL DEFAULT '{}',
  "result" TEXT,
  "error" TEXT,
  "availableAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "leaseExpiresAt" DATETIME,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Job_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Job_idempotencyKey_key" ON "Job"("idempotencyKey");
CREATE INDEX IF NOT EXISTS "Job_status_availableAt_idx" ON "Job"("status", "availableAt");
CREATE TABLE IF NOT EXISTS "AuditLog" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT,
  "userId" TEXT,
  "action" TEXT NOT NULL,
  "target" TEXT,
  "detail" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditLog_academyId_fkey" FOREIGN KEY ("academyId") REFERENCES "Academy" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "AuditLog_academyId_createdAt_idx" ON "AuditLog"("academyId", "createdAt");
CREATE TABLE IF NOT EXISTS "DeviceToken" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "platform" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "DeviceToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "DeviceToken_token_key" ON "DeviceToken"("token");
CREATE TABLE IF NOT EXISTS "Notification" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "link" TEXT,
  "read" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "Notification_userId_read_idx" ON "Notification"("userId", "read");
CREATE TABLE IF NOT EXISTS "UsageEvent" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "academyId" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "amount" INTEGER NOT NULL DEFAULT 1,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "UsageEvent_academyId_kind_createdAt_idx" ON "UsageEvent"("academyId", "kind", "createdAt");
